### ISSUE TITLE
Documentation: how to add a python dictionary to Plover

### ISSUE THREAD

**Issue by chauser** [benoit-pierre/plover_python_dictionary#2]
A suggestion for a small documentation change: 

Suppose you have added this plugin and you have a python dictionary in hand. I couldn't find any place that documents what you are supposed to do to start using the dictionary. Of course the answer is very simple once you know it: simply add the .py file using the same dialog that you use to add any other dictionary to plover -- .py is a supported extension. A one-sentence addition to the readme.rst might help others to avoid the search.

"After installing the plover-python-dictionary plugin with the Plugins Manager, python modules that implement the plover-python-dictionary interface can be added to plover using the Edit|Add dictionaries|Open dictionaries menu item." 

Thanks Benoit-Pierre for this plugin -- the show_stroke.py python dictionary all by itself justifies the need for this.

**Comment by benoit-pierre** [comment]
Fixed by ef7abac.
