### ISSUE TITLE
Add ability to import dictionaries from dictionaries

### ISSUE THREAD

**Issue by nvdaes** [benoit-pierre/plover_python_dictionary#5]
With Plover supporting Melani system, it's possible to assign two different translations to a stroke deppending on the next translation. However, this is not enough for languages which have irregular verbs or similar.

Example: in Spanish, PCTcs followed by  "as or an ", or followed by "amos" or by "b or s", or by "e" should be translated in different ways. To support this, a global variable from the dictionary with lowest priority (with LONGEST_KEY = 1) can be used and modified by a dictionary with LONGEST_KEY = 2 and higher priority.
For example, please see the [Plover_spanish_mqd plugin](https://github.com/nvdaes/plover_spanish_mqd)

If this cannot be implemented, I'll use version 0.5.10 of this plugin.

Thanks.

**Comment by benoit-pierre** [comment]
What I don't understand from your [system definition](https://github.com/nvdaes/plover_spanish_mqd/blob/main/plover_spanish_mqd/system.py#L196), is why you don't just use 1 dictionary?

**Comment by nvdaes** [comment]
> 
> 
> What I don't understand from your [system definition](https://github.com/nvdaes/plover_spanish_mqd/blob/main/plover_spanish_mqd/system.py#L196), is why you don't just use 1 dictionary?

Oh, I may try to do it. In part for better organization of archives and since sometimes it's not needed to use LONGEST_KEY = 2.

I'll try again and in the meantime I'll use 0.5.10 version of the plugin.

**Comment by benoit-pierre** [comment]
OK, so I'll leave this open for now.

**Comment by nvdaes** [comment]
I'll take care of this issue and will inform about my results when I can try to use a unique dictionary. Anyway, some kind of import maybe convenient to avoid too long files.
Thanks

**Comment by benoit-pierre** [comment]
You can import, but not other dictionaries.

**Comment by nvdaes** [comment]
> 
> 
> You can import, but not other dictionaries.

OK, then I'll try to import Python files containing Python dictionaries, not Plover dictionaries.
I'll come back here with results.

**Comment by nvdaes** [comment]
I've performed two kind of tests without good results:

1. Trying to import modules from a dictionary. I've copied them in the default dictionaries folder, but they haven't been copied when I installed the plugin locally.
1. I've created a dictionary containing all required data, such as methods and Python dictionaries. The problem with this approach (even if modules could be imported and copied properly) is that LONGEST_KEY = 2, and, for each sequence of pressed strokes, translations aren't shown in the first stroke and we should press the second one so that Plover can write them.

You can see this [pull request using one dictionary](https://github.com/nvdaes/plover_spanish_mqd/pull/1).

Thanks

**Comment by benoit-pierre** [comment]
I'm sorry, but I'm still not entirely clear on what it is you're trying do do. Are you actually relying in the fact that the `spanish_mqd_single` module instance is not the same in each instance of the `spanish_mqd_double` / `spanish_mqd_single` loaded Python dictionaries?

It would help if you could provide some exact tests, a [blackbox like test](https://github.com/openstenoproject/plover/blob/master/test/test_blackbox.py):
```python
first_stroke        " output state"
second_stroke  " new output state"
```

On another note, you can use absolute paths to prevent Plover from creating a copy of one of the system dictionaries in the config dir:
```diff
diff --git i/plover_spanish_mqd/system.py w/plover_spanish_mqd/system.py
index 4d71662..e780096 100644
--- i/plover_spanish_mqd/system.py
+++ w/plover_spanish_mqd/system.py
@@ -193,4 +193,6 @@
 KEYMAPS['Stentura (Italian version)'] = KEYMAPS['Stentura']
 
 DICTIONARIES_ROOT = 'asset:plover_spanish_mqd:dictionaries'
-DEFAULT_DICTIONARIES = ('user_es.json', 'punctuation.json', 'initial.json', 'spanish_mqd_double.py', 'spanish_mqd_single.py')
+DEFAULT_DICTIONARIES = ('user_es.json', 'punctuation.json', 'initial.json',
+                        DICTIONARIES_ROOT + '/spanish_mqd_double.py',
+                        DICTIONARIES_ROOT + '/spanish_mqd_single.py')
```

**Comment by nvdaes** [comment]
> 
> 
> I'm sorry, but I'm still not entirely clear on what it is you're trying do do. Are you actually relying in the fact that the `spanish_mqd_single` module instance is not the same in each instance of the `spanish_mqd_double` / `spanish_mqd_single` loaded Python dictionaries?

Yes, the global lastValue is contained in `spanish_mqd_single` and modified by `spanish_mqd_double`, which has a LONGEST_KEY = 2. Then, if I press a keystroke that is not addressed in this dictionary, Plover raises a KeyError to search in `spanish_mqd_single`, which has LONGEST_KEY = 1 and lower priority.

I'll perform the test you suggest me instead of my unit tests and follow any other suggestion you may provide. This is absolutely crucial for my job, since we aren't maintaining the old Microsoft database of a proprietary software named Winsteno, which is not updated and requires a license, and I have different events in real time very often, which require that Plover works as expected for me.
Thanks for your attention

**Comment by benoit-pierre** [comment]
But those 2 Python dictionaries end-up using different module instances of `spanish_mqd_single`:
```diff
 plover_spanish_mqd/dictionaries/spanish_mqd_double.py | 4 ++++
 plover_spanish_mqd/dictionaries/spanish_mqd_single.py | 3 +++
 2 files changed, 7 insertions(+)

diff --git i/plover_spanish_mqd/dictionaries/spanish_mqd_double.py w/plover_spanish_mqd/dictionaries/spanish_mqd_double.py
index 37f5001..4271201 100644
--- i/plover_spanish_mqd/dictionaries/spanish_mqd_double.py
+++ w/plover_spanish_mqd/dictionaries/spanish_mqd_double.py
@@ -1,9 +1,12 @@
 import os
 import sys
 sys.path.append(os.path.dirname(__file__))
+print('double', 'import spanish_mqd_single')
 import spanish_mqd_single
+print('double', id(spanish_mqd_single.numbers))
 del sys.path[-1]
 
+
 LONGEST_KEY = 2
 
 VOWELS = ("a", "á", "e", "é", "i", "í", "o", "ó", "u", "ú")
@@ -803,6 +806,7 @@
 }
 
 def lookup(key):
+	print('double.lookup', id(spanish_mqd_single.numbers))
 	if doubleStrokes.get(key[0]) is None:
 		raise KeyError
 	spanish_mqd_single.lastValue = doubleStrokes.get(key[0])
diff --git i/plover_spanish_mqd/dictionaries/spanish_mqd_single.py w/plover_spanish_mqd/dictionaries/spanish_mqd_single.py
index 68214b5..b066588 100644
--- i/plover_spanish_mqd/dictionaries/spanish_mqd_single.py
+++ w/plover_spanish_mqd/dictionaries/spanish_mqd_single.py
@@ -14,6 +14,8 @@
 	"i": "9"
 }
 
+print('single', id(numbers), '[%s]' % __name__)
+
 dict = {
 	"a": ("", "a "),
 	"A": ("", "a"),
@@ -11739,6 +11741,7 @@ def searchKey(dictionary, stroke):
 
 
 def lookup(key):
+	print('single.lookup', id(numbers), '[%s]' % __name__)
 	value = ""
 	# Numbers
 	if "#" in key[0]:
```
And some of the output:
```
double import spanish_mqd_single
single 22992643222720 [spanish_mqd_single]
double 22992643222720
single 22992643221312 []
double.lookup 22992643222720
double.lookup 22992643222720
single.lookup 22992643221312 []
double.lookup 22992643222720
double.lookup 22992643222720
single.lookup 22992643221312 []
```

If you wanted to combine the dictionaries, here's how to replicate the behavior of Plover' `StenoDictionaryCollection`:
```diff
 plover_spanish_mqd/dictionaries/__init__.py           |  0
 plover_spanish_mqd/dictionaries/spanish_mqd.py        | 19 +++++++++++++++++++
 .../{dictionaries => }/spanish_mqd_double.py          |  7 ++-----
 .../{dictionaries => }/spanish_mqd_single.py          |  0
 plover_spanish_mqd/system.py                          |  2 +-
 tests/test_double.py                                  |  4 ++--
 tests/test_single.py                                  |  2 +-
 7 files changed, 25 insertions(+), 9 deletions(-)

diff --git a/plover_spanish_mqd/dictionaries/__init__.py b/plover_spanish_mqd/dictionaries/__init__.py
deleted file mode 100644
index e69de29..0000000
diff --git a/plover_spanish_mqd/dictionaries/spanish_mqd.py b/plover_spanish_mqd/dictionaries/spanish_mqd.py
new file mode 100644
index 0000000..fd87e95
--- /dev/null
+++ b/plover_spanish_mqd/dictionaries/spanish_mqd.py
@@ -0,0 +1,19 @@
+from plover_spanish_mqd import (
+    spanish_mqd_double as double,
+    spanish_mqd_single as single,
+)
+
+
+DICTIONARIES = [double, single]
+
+LONGEST_KEY = max(d.LONGEST_KEY for d in DICTIONARIES)
+
+def lookup(key):
+    for d in DICTIONARIES:
+        if len(key) > d.LONGEST_KEY:
+            continue
+        try:
+            return d.lookup(key)
+        except KeyError:
+            pass
+    raise KeyError
diff --git a/plover_spanish_mqd/dictionaries/spanish_mqd_double.py b/plover_spanish_mqd/spanish_mqd_double.py
similarity index 99%
rename from plover_spanish_mqd/dictionaries/spanish_mqd_double.py
rename to plover_spanish_mqd/spanish_mqd_double.py
index 37f5001..32693c0 100644
--- a/plover_spanish_mqd/dictionaries/spanish_mqd_double.py
+++ b/plover_spanish_mqd/spanish_mqd_double.py
@@ -1,8 +1,5 @@
-import os
-import sys
-sys.path.append(os.path.dirname(__file__))
-import spanish_mqd_single
-del sys.path[-1]
+from . import spanish_mqd_single
+
 
 LONGEST_KEY = 2
 
diff --git a/plover_spanish_mqd/dictionaries/spanish_mqd_single.py b/plover_spanish_mqd/spanish_mqd_single.py
similarity index 100%
rename from plover_spanish_mqd/dictionaries/spanish_mqd_single.py
rename to plover_spanish_mqd/spanish_mqd_single.py
diff --git a/plover_spanish_mqd/system.py b/plover_spanish_mqd/system.py
index 4d71662..a6a28d7 100644
--- a/plover_spanish_mqd/system.py
+++ b/plover_spanish_mqd/system.py
@@ -193,4 +193,4 @@
 KEYMAPS['Stentura (Italian version)'] = KEYMAPS['Stentura']
 
 DICTIONARIES_ROOT = 'asset:plover_spanish_mqd:dictionaries'
-DEFAULT_DICTIONARIES = ('user_es.json', 'punctuation.json', 'initial.json', 'spanish_mqd_double.py', 'spanish_mqd_single.py')
+DEFAULT_DICTIONARIES = ('user_es.json', 'punctuation.json', 'initial.json', 'spanish_mqd.py')
diff --git a/tests/test_double.py b/tests/test_double.py
index ac4c358..43a261a 100644
--- a/tests/test_double.py
+++ b/tests/test_double.py
@@ -1,6 +1,6 @@
 import unittest
-from plover_spanish_mqd.dictionaries import spanish_mqd_single
-from plover_spanish_mqd.dictionaries import spanish_mqd_double
+from plover_spanish_mqd import spanish_mqd_single
+from plover_spanish_mqd import spanish_mqd_double
 from plover_spanish_mqd import system
 
 
diff --git a/tests/test_single.py b/tests/test_single.py
index a04b9aa..6db45f8 100644
--- a/tests/test_single.py
+++ b/tests/test_single.py
@@ -1,5 +1,5 @@
 import unittest
-from plover_spanish_mqd.dictionaries import spanish_mqd_single
+from plover_spanish_mqd import spanish_mqd_single
 from plover_spanish_mqd import system
 

```

**Comment by benoit-pierre** [comment]
Regarding the Winsteno stuff, I'll be publishing the Melani plugin shortly (as soon as I have RC of Plover I can depend on). The plugin includes some code to convert a Winsteno dictionary.

**Comment by benoit-pierre** [comment]
Again, just give me one high level blackbox like test example, so I can create an actual test for you and really investigate the issue. (The blackbox tests framework will need to be tweaked a little I think).

**Comment by nvdaes** [comment]
Hello, I've created the requested test as an example, based on the corresponding file in Plover without deleting code. I'm not sure if this would be useful. Please, see the Spanish MQD class in tests/test_blackbox.py. I've done it in the PR created for testing.
I'll do the changes you feel that maybe useful, even in the main branch of the repo.

https://github.com/nvdaes/plover_spanish_mqd/pull/1/files

Thanks

**Comment by nvdaes** [comment]
Hi again, in case my created test is not useful due to serious failures: I've tried to build plover from source to refine my tests, but I installed Python 3.8 since the program was updated to use this version, I think, but instructions for development seem not to be updated. I'm not sure if in the tests is mandatory to include the translation corresponding to keystrokes. I think it shouldn't be needed knowing how to provide the dictionaries.
I may provide tests for other irregular verbs and so on, but I think it's better to way for your feedback. I prefer to clarify this since I'm afraid that the tests provided by me are not good at all, and also in case the documentation about development needs to be updated (not sure).
Also, note that order and name of keys are not exactly equal to the original Melani system.
Kind regards

**Comment by benoit-pierre** [comment]
See [here for WIP](https://github.com/nvdaes/plover_spanish_mqd/compare/main...benoit-pierre:incubation):

* first 2 commits for comfort: [add tox configuration](https://github.com/nvdaes/plover_spanish_mqd/commit/92534297ad24c8a4233933a8a72c17bb6e593f95) and [`test` extra](https://github.com/nvdaes/plover_spanish_mqd/commit/10a0d7f35ca125efb189e6753bf07fd994381c84)
* then a [temporary pin of `plover-python-dictionary` to an older version](https://github.com/nvdaes/plover_spanish_mqd/commit/0566951487801da75825b6fb55aecbe01ca85382)
* then [add the framework for the blackbox tests](https://github.com/nvdaes/plover_spanish_mqd/commit/588695b39b01216bcdb4765dfbfee4997b7db33a). I use a development wheel of Plover to get the required blackbox test support. The framework ensure the 2 Python dictionaries are enabled for each run, other entries that would normally be provided by the JSON dictionaries must still be provided at the top of each test (like the mapping for the undo stroke). All 3 tests fail for different reasons:
  - `test_regular_verb_1`: invalid steno/stroke (`TPVa`)
  - `test_regular_verb_2`: final output is not correct (` lleguen é` instead of ` llegué`)
  - `test_irregular_1`: final output it not correct either (` juguéando` instead of ` jugando`)
* and finally the [attempt at providing only one unified Python dictionary](https://github.com/nvdaes/plover_spanish_mqd/commit/4330fe3d883f448e412ea96f36fa6a5032b07ffc): same results with the blackbox tests, so at least it's consistent

IMHO the next step would be to fix the blackbox tests on https://github.com/nvdaes/plover_spanish_mqd/commit/588695b39b01216bcdb4765dfbfee4997b7db33a, to have a baseline, than ensure the merged dictionary approach on https://github.com/nvdaes/plover_spanish_mqd/commit/4330fe3d883f448e412ea96f36fa6a5032b07ffc works too, before unpinning `plover-python-dictionary` to check if it works with the latest version too.

**Comment by nvdaes** [comment]
Hello, thanks so much.

> - test_regular_verb_1: invalid steno/stroke (TPVa)

My mistake. Valid stroke is PTVa. I'll see other tests and try to fix things in my repo according to your feedback.º

**Comment by nvdaes** [comment]
Hi again, I've fixed several mistakes in tests from my part and now all works well with version 1.0.0 of this plugin.
I'm so grateful for your attention! Thanks so much.
Now I have a problem, but seems it's not related to these changes, since the problem persists when I install the releases Plover_spanish_mqd regardless of the version of this plugin. Now i cannot set the number of keystrokes to be undone, since Plover doesn't recognize these number and words instead of translations are deleted. Tomorrow I'll test in my job.
You can see the main branch of plover_spanish_mqd again if you want:

https://github.com/nvdaes/plover_spanish_mqd

Thanks so much.

**Comment by benoit-pierre** [comment]
Great, I'll close this issue.
