### ISSUE TITLE
[Feature request] Allow setting load time-out for dictionaries

### ISSUE THREAD

**Issue by user202729** [benoit-pierre/plover_python_dictionary#6]
Reason: I usually use `/tmp/a.py` for a temporary file, but I also put other non-dictionary things there, so occasionally Plover might hang trying to execute that file...

Having the plugin report "dictionary load takes too long (with a configurable timeout)" is better than having Plover hangs indefinitely.

*Alternatively...*

Make Plover show the "refreshing" state for only the actually-loading dictionaries on startup, instead of all of them.

**Comment by benoit-pierre** [comment]
> [...] but I also put other non-dictionary things there, [...]

Or better yet, avoid doing that? What if that file contains a destructive operation?

Anyway, I'm not going to make the code more complex for that use case.
