### ISSUE TITLE
Is there a way for a python dict to modify an incoming stroke?

### ISSUE THREAD

**Issue by AntoineBalaine** [benoit-pierre/plover_python_dictionary#8]
Is there a way for a python dict to modify an incoming stroke?

Let's say I finish a stroke with a `;` (my steno system has punctuation) and I'm trying to have the dict pass on the the beginning of the stroke, but then add the `;` at the end of the output word. 

Basically: `PA/PA;` would output `PA/PA/;`

**Comment by benoit-pierre** [comment]
No, a Python dictionary maps strokes to translations, like standard dictionaries.

**Comment by benoit-pierre** [comment]
Assuming https://github.com/AntoineBalaine/bepo-steno is the system your speaking about, why don't you use the support for suffix keys? Example:
```diff
diff --git i/plover_bepo/system.py w/plover_bepo/system.py
index c304a7e..ac92cc1 100644
--- i/plover_bepo/system.py
+++ w/plover_bepo/system.py
@@ -7,7 +7,7 @@ KEYS = (
 '#', 'ß', 'H', '.', ','
  )
 IMPLICIT_HYPHEN_KEYS = KEYS
-SUFFIX_KEYS = ()
+SUFFIX_KEYS = ('.', ',')
 NUMBER_KEY = None
 NUMBERS = {}
 UNDO_STROKE_STENO = '*'
```
Add `,` → `{,}` to the dictionary, and `PA/PA,` will be automatically translated as `papa{,}`.

Notes:
- the `SténoTroisièmeGroupe.json` and `prépositions.json` dictionaries referenced in your system are missing from the repository
- `plover_bepo.egg-info` directory generated by setuptools should really not be versioned

**Comment by AntoineBalaine** [comment]
Perfect! Thank you very much!
